CREATE TABLE CG (
    CG_ID NUMBER(20),
    CG_TITLE VARCHAR2(30),
    CG_TYPE VARCHAR2(30),
    USERID ??,
    CG_CONTENT VARCHAR2(2048),
    WRITE_DATE SYSDATE,
    EDIT_DATE SYSDATE,
    CHECK NUMBER(30),
    FILE ??,
    

);
