CREATE TABLE BBS_T (
	B_IDX NUMBER(6) CONSTRAINT BBS_T_PK PRIMARY KEY,
	SUBJECT VARCHAR2(50), --글제목
	WRITER VARCHAR2(20), --작성자
	CONTENT CLOB, --글내용
    --문자 대형 객체 (Character). Oracle Server는 CLOB과 VARCHAR2 사이에 암시적 변환을 수행한다.
	FILE_NAME VARCHAR2(50), --실제 저장되는 파일명
	ORI_NAME VARCHAR2(50), --원본 파일명
	PWD VARCHAR2(20), --암호
	WRITE_DATE DATE, --작성일시
	IP VARCHAR2(15), --작성자 IP주소
	HIT NUMBER(4) --조회수
);

--게시글에 대한 댓글(COMMENT_T)
CREATE TABLE COMMENT_T (
	C_IDX NUMBER(6) CONSTRAINT COMM_T_PK PRIMARY KEY, --제약 조건 & 제약 조건 이름!!
	WRITER VARCHAR2(20),
	CONTENT CLOB,
	PWD VARCHAR2(20),
	WRITE_DATE DATE,
	IP VARCHAR2(15),
	B_IDX NUMBER(6), --게시글 번호
	CONSTRAINT COMM_T_FK FOREIGN KEY (B_IDX) REFERENCES BBS_T(B_IDX)
);